In [1]:
import json
import os
import pandas as pd

In [2]:

files = [
    "datasets/problem.json",
    "datasets/student-problem-fine.json",
    "datasets/student-problem-coarse.json",
    "datasets/student-problem-middle.json"
]

base_path = "/Users/muazalbaghdadi/Documents/Work/Reasearch/UDST/Gamification/MOOCRadar"

In [8]:
# Define paths (assuming base_path and files list are already defined)
file_path = os.path.join(base_path, files[3])
# Load and flatten the nested JSON sequences
with open(file_path, "r", encoding="utf-8") as f:
    student_data = json.load(f)
# Flatten the nested "seq" list for each student
df_middle = pd.json_normalize(student_data, record_path="seq")
# Display the first few rows and the DataFrame shape
print(f"'student-problem-middle.json' DataFrame Shape: {df_middle.shape}")
df_middle.head()

'student-problem-middle.json' DataFrame Shape: (898933, 9)

,log_id,problem_id,user_id,is_correct,attempts,score,submit_time,skill_id,exercise_id
0,1002476_5940094,Pm_668265,U_1002476,1,1,NaN,2020-12-13 12:02:59,Ex_535149,Ex_535149
1,1002476_5940096,Pm_668266,U_1002476,1,1,NaN,2020-12-13 12:03:11,Ex_535149,Ex_535149
2,1002476_5940097,Pm_668267,U_1002476,1,1,NaN,2020-12-13 12:03:18,Ex_535149,Ex_535149
3,1002476_5940102,Pm_668268,U_1002476,1,1,NaN,2020-12-13 12:11:10,Ex_535150,Ex_535150
4,1002476_5940103,Pm_668269,U_1002476,1,1,NaN,2020-12-13 12:11:21,Ex_535150,Ex_535150

In [ ]:

df_middle.dtypes

log_id          object
problem_id      object
user_id         object
is_correct       int64
attempts         int64
score          float64
submit_time     object
skill_id        object
exercise_id     object
dtype: object

student-problem-coarse.json EDA

In [56]:
# Define paths (assuming base_path and files list are already defined)
file_path = os.path.join(base_path, files[2])
# Load and flatten the nested JSON sequences
with open(file_path, "r", encoding="utf-8") as f:
    student_data = json.load(f)
# Flatten the nested "seq" list for each student
df_coarse = pd.json_normalize(student_data, record_path="seq")
# Display the first few rows and the DataFrame shape
print(f"'student-problem-coarse.json' DataFrame Shape: {df_middle.shape}")
df_coarse.head()

'student-problem-coarse.json' DataFrame Shape: (898933, 9)

,log_id,problem_id,user_id,is_correct,attempts,score,submit_time,skill_id,course_id
0,1002476_5940094,Pm_668265,U_1002476,1,1,NaN,2020-12-13 12:02:59,C_697360,C_697360
1,1002476_5940096,Pm_668266,U_1002476,1,1,NaN,2020-12-13 12:03:11,C_697360,C_697360
2,1002476_5940097,Pm_668267,U_1002476,1,1,NaN,2020-12-13 12:03:18,C_697360,C_697360
3,1002476_5940102,Pm_668268,U_1002476,1,1,NaN,2020-12-13 12:11:10,C_697360,C_697360
4,1002476_5940103,Pm_668269,U_1002476,1,1,NaN,2020-12-13 12:11:21,C_697360,C_697360

In [12]:
df_coarse.dtypes

log_id          object
problem_id      object
user_id         object
is_correct       int64
attempts         int64
score          float64
submit_time     object
skill_id        object
course_id       object
dtype: object

In [57]:
list(df_coarse)

['log_id',
 'problem_id',
 'user_id',
 'is_correct',
 'attempts',
 'score',
 'submit_time',
 'skill_id',
 'course_id']

In [65]:
df_coarse['course_id'].unique()

array(['C_697360', 'C_674920', 'C_1741511', 'C_696922', 'C_770738',
       'C_756646', 'C_697821', 'C_746997', 'C_797404', 'C_735239',
       'C_697766', 'C_758928', 'C_948099', 'C_2287011', 'C_676937',
       'C_697791', 'C_696679', 'C_949541', 'C_676705', 'C_1696158',
       'C_707135', 'C_696724', 'C_680980', 'C_697113'], dtype=object)

In [67]:
df_coarse['course_id'].describe()

count        898933
unique           24
top       C_2287011
freq         384935
Name: course_id, dtype: object

student-problem-fine.json EDA

In [10]:
# Define paths (assuming base_path and files list are already defined)
file_path = os.path.join(base_path, files[1])
# Load and flatten the nested JSON sequences
with open(file_path, "r", encoding="utf-8") as f:
    student_data = json.load(f)
# Flatten the nested "seq" list for each student
df_fine = pd.json_normalize(student_data, record_path="seq")
# Display the first few rows and the DataFrame shape
print(f"'student-problem-fine.json' DataFrame Shape: {df_middle.shape}")
df_fine.head()

'student-problem-fine.json' DataFrame Shape: (898933, 9)

,log_id,problem_id,user_id,is_correct,attempts,score,submit_time
0,1002476_5940094,Pm_668265,U_1002476,1,1,NaN,2020-12-13 12:02:59
1,1002476_5940096,Pm_668266,U_1002476,1,1,NaN,2020-12-13 12:03:11
2,1002476_5940097,Pm_668267,U_1002476,1,1,NaN,2020-12-13 12:03:18
3,1002476_5940102,Pm_668268,U_1002476,1,1,NaN,2020-12-13 12:11:10
4,1002476_5940103,Pm_668269,U_1002476,1,1,NaN,2020-12-13 12:11:21

In [13]:
df_fine.dtypes

log_id          object
problem_id      object
user_id         object
is_correct       int64
attempts         int64
score          float64
submit_time     object
dtype: object

In [45]:
list(df_fine)

['log_id',
 'problem_id',
 'user_id',
 'is_correct',
 'attempts',
 'score',
 'submit_time']

In [48]:
df_fine['is_correct'].unique()

array([1, 0])

In [49]:
df_fine['is_correct'].value_counts()

is_correct
1    733096
0    165837
Name: count, dtype: int64

In [55]:
df_fine['is_correct'].describe()

count    898933.000000
mean          0.815518
std           0.387877
min           0.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: is_correct, dtype: float64

problem.json EDA

In [14]:

# Load files[0] (problem.json)
file_path = os.path.join(base_path, files[0])
df_problems = pd.read_json(file_path, lines=True)
print(f"'problem.json' Problems DataFrame Shape: {df_problems.shape}")
df_problems.head()

'problem.json' Problems DataFrame Shape: (9383, 7)

,problem_id,exercise_id,course_id,detail,knowledge_type,cognitive_dimension,concepts
0,Pm_2046133,Ex_1641736,C_674920,"{'problem_id': 2046133, 'title': '第一章作业', 'con...",2,4,"[经济发展逻辑, 逻辑学]"
1,Pm_2046134,Ex_1641736,C_674920,"{'problem_id': 2046134, 'title': '第一章作业', 'con...",2,2,"[希腊语, 逻辑]"
2,Pm_2046135,Ex_1641736,C_674920,"{'problem_id': 2046135, 'title': '第一章作业', 'con...",2,2,"[逻辑, 推理]"
3,Pm_2046136,Ex_1641736,C_674920,"{'problem_id': 2046136, 'title': '第一章作业', 'con...",2,2,"[演绎推理, 推理, 结论]"
4,Pm_2046137,Ex_1641736,C_674920,"{'problem_id': 2046137, 'title': '第一章作业', 'con...",2,2,"[命题, 有效推理形式]"

In [15]:
df_problems.dtypes

problem_id             object
exercise_id            object
course_id              object
detail                 object
knowledge_type          int64
cognitive_dimension     int64
concepts               object
dtype: object

In [17]:
df_problems.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9383 entries, 0 to 9382
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   problem_id           9383 non-null   object
 1   exercise_id          9383 non-null   object
 2   course_id            9383 non-null   object
 3   detail               9383 non-null   object
 4   knowledge_type       9383 non-null   int64
 5   cognitive_dimension  9383 non-null   int64
 6   concepts             9383 non-null   object
dtypes: int64(2), object(5)
memory usage: 513.3+ KB

In [21]:
list(df_problems)

['problem_id',
 'exercise_id',
 'course_id',
 'detail',
 'knowledge_type',
 'cognitive_dimension',
 'concepts']

In [68]:
df_problems['cognitive_dimension'].value_counts()

cognitive_dimension
2    4401
3    1991
1    1836
4     759
5     364
6      32
Name: count, dtype: int64

In [69]:
df_problems['cognitive_dimension'].unique()

array([4, 2, 5, 1, 3, 6])

In [70]:
df_problems['cognitive_dimension'].nunique()

6

In [40]:
df_problems.describe()

       knowledge_type  cognitive_dimension
count     9383.000000          9383.000000
mean         2.101567             2.308324
std          0.760082             1.019895
min          1.000000             1.000000
25%          2.000000             2.000000
50%          2.000000             2.000000
75%          3.000000             3.000000
max          4.000000             6.000000

In [37]:
df_problems.shape

(9383, 7)

In [71]:
df_problems['knowledge_type'].value_counts()

knowledge_type
2    4331
3    2770
1    2127
4     155
Name: count, dtype: int64

In [72]:
df_problems['knowledge_type'].unique()

array([2, 1, 3, 4])