In [1]:
import json
import os
import pandas as pd

In [2]:

files = [
    "datasets/problem.json",
    "datasets/student-problem-fine.json",
    "datasets/student-problem-coarse.json",
    "datasets/student-problem-middle.json"
]

base_path = "/Users/muazalbaghdadi/Documents/Work/Reasearch/UDST/Gamification/MOOCRadar"

In [18]:
df_problems = pd.read_json(os.path.join(base_path, files[0]), lines=True)

# Loading Fine to DF
file_path = os.path.join(base_path, files[1])
# Load and flatten the nested JSON sequences
with open(file_path, "r", encoding="utf-8") as f:
    student_data = json.load(f)
# Flatten the nested "seq" list for each student
df_fine = pd.json_normalize(student_data, record_path="seq")

# Loading Coarse to DF
file_path = os.path.join(base_path, files[2])
# Load and flatten the nested JSON sequences
with open(file_path, "r", encoding="utf-8") as f:
    student_data = json.load(f)
# Flatten the nested "seq" list for each student
df_coarse = pd.json_normalize(student_data, record_path="seq")

# Loading Middle to DF
file_path = os.path.join(base_path, files[3])
# Load and flatten the nested JSON sequences
with open(file_path, "r", encoding="utf-8") as f:
    student_data = json.load(f)
# Flatten the nested "seq" list for each student
df_middle = pd.json_normalize(student_data, record_path="seq")

In [24]:
print('df_problems info and head')
df_problems.info()
df_problems.head()

df_problems info and head
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9383 entries, 0 to 9382
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   problem_id           9383 non-null   object
 1   exercise_id          9383 non-null   object
 2   course_id            9383 non-null   object
 3   detail               9383 non-null   object
 4   knowledge_type       9383 non-null   int64
 5   cognitive_dimension  9383 non-null   int64
 6   concepts             9383 non-null   object
dtypes: int64(2), object(5)
memory usage: 513.3+ KB

,problem_id,exercise_id,course_id,detail,knowledge_type,cognitive_dimension,concepts
0,Pm_2046133,Ex_1641736,C_674920,"{'problem_id': 2046133, 'title': '第一章作业', 'con...",2,4,"[经济发展逻辑, 逻辑学]"
1,Pm_2046134,Ex_1641736,C_674920,"{'problem_id': 2046134, 'title': '第一章作业', 'con...",2,2,"[希腊语, 逻辑]"
2,Pm_2046135,Ex_1641736,C_674920,"{'problem_id': 2046135, 'title': '第一章作业', 'con...",2,2,"[逻辑, 推理]"
3,Pm_2046136,Ex_1641736,C_674920,"{'problem_id': 2046136, 'title': '第一章作业', 'con...",2,2,"[演绎推理, 推理, 结论]"
4,Pm_2046137,Ex_1641736,C_674920,"{'problem_id': 2046137, 'title': '第一章作业', 'con...",2,2,"[命题, 有效推理形式]"

In [25]:
print('df_fine info and head')
df_fine.info()
df_fine.head()

df_fine info and head
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898933 entries, 0 to 898932
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   log_id       898933 non-null  object
 1   problem_id   898933 non-null  object
 2   user_id      898933 non-null  object
 3   is_correct   898933 non-null  int64
 4   attempts     898933 non-null  int64
 5   score        355086 non-null  float64
 6   submit_time  898933 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 48.0+ MB

,log_id,problem_id,user_id,is_correct,attempts,score,submit_time
0,1002476_5940094,Pm_668265,U_1002476,1,1,NaN,2020-12-13 12:02:59
1,1002476_5940096,Pm_668266,U_1002476,1,1,NaN,2020-12-13 12:03:11
2,1002476_5940097,Pm_668267,U_1002476,1,1,NaN,2020-12-13 12:03:18
3,1002476_5940102,Pm_668268,U_1002476,1,1,NaN,2020-12-13 12:11:10
4,1002476_5940103,Pm_668269,U_1002476,1,1,NaN,2020-12-13 12:11:21

In [26]:
print('df_coarse info and head')
df_coarse.info()
df_coarse.head()

df_coarse info and head
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898933 entries, 0 to 898932
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   log_id       898933 non-null  object
 1   problem_id   898933 non-null  object
 2   user_id      898933 non-null  object
 3   is_correct   898933 non-null  int64
 4   attempts     898933 non-null  int64
 5   score        355086 non-null  float64
 6   submit_time  898933 non-null  object
 7   skill_id     898933 non-null  object
 8   course_id    898933 non-null  object
dtypes: float64(1), int64(2), object(6)
memory usage: 61.7+ MB

,log_id,problem_id,user_id,is_correct,attempts,score,submit_time,skill_id,course_id
0,1002476_5940094,Pm_668265,U_1002476,1,1,NaN,2020-12-13 12:02:59,C_697360,C_697360
1,1002476_5940096,Pm_668266,U_1002476,1,1,NaN,2020-12-13 12:03:11,C_697360,C_697360
2,1002476_5940097,Pm_668267,U_1002476,1,1,NaN,2020-12-13 12:03:18,C_697360,C_697360
3,1002476_5940102,Pm_668268,U_1002476,1,1,NaN,2020-12-13 12:11:10,C_697360,C_697360
4,1002476_5940103,Pm_668269,U_1002476,1,1,NaN,2020-12-13 12:11:21,C_697360,C_697360

In [27]:
print('df_middle info and head')
df_middle.info()
df_middle.head()

df_middle info and head
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898933 entries, 0 to 898932
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   log_id       898933 non-null  object
 1   problem_id   898933 non-null  object
 2   user_id      898933 non-null  object
 3   is_correct   898933 non-null  int64
 4   attempts     898933 non-null  int64
 5   score        355086 non-null  float64
 6   submit_time  898933 non-null  object
 7   skill_id     898933 non-null  object
 8   exercise_id  898933 non-null  object
dtypes: float64(1), int64(2), object(6)
memory usage: 61.7+ MB

,log_id,problem_id,user_id,is_correct,attempts,score,submit_time,skill_id,exercise_id
0,1002476_5940094,Pm_668265,U_1002476,1,1,NaN,2020-12-13 12:02:59,Ex_535149,Ex_535149
1,1002476_5940096,Pm_668266,U_1002476,1,1,NaN,2020-12-13 12:03:11,Ex_535149,Ex_535149
2,1002476_5940097,Pm_668267,U_1002476,1,1,NaN,2020-12-13 12:03:18,Ex_535149,Ex_535149
3,1002476_5940102,Pm_668268,U_1002476,1,1,NaN,2020-12-13 12:11:10,Ex_535150,Ex_535150
4,1002476_5940103,Pm_668269,U_1002476,1,1,NaN,2020-12-13 12:11:21,Ex_535150,Ex_535150